# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Bluejay Documentation
description: >- # this means to ignore newlines until "baseurl:"
  Everything you always wanted to know about everyones
  favourite 8 Bit ESC firmware. More details than you can handle: Flow-charts
  and walls of text.
baseurl: "/bluejay-documentation/" # the subpath of your site, e.g. /blog
url: "https://bird-sanctuary.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  bird-sanctuary
github_bluejay_url: https://github.com/mathiasvr/bluejay

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

include: ['_pages']

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
