@startuml 
split
  -[hidden]->
  :beep_f1;
  :Temp3 = 66;
  :Temp4 = 3500 / 66;
split again
  -[hidden]->
  :beep_f2;
  :Temp3 = 45;
  :Temp4 = 3500 / 45;
split again
  -[hidden]->
  :beep_f3;
  :Temp3 = 38;
  :Temp4 = 3500 / 38;
split again
  -[hidden]->
  :beep_f4;
  :Temp3 = 25;
  :Temp4 = 3500 / 25;
split again
  -[hidden]->
  :beep_f5;
  :Temp3 = 20;
  :Temp4 = 3500 / 20;
split again
  -[hidden]->
  :beep_f1_short;
  :Temp3 = 66;
  :Temp4 = 2000 / 66;
split again
  -[hidden]->
  :beep_f2_short;
  :Temp3 = 45;
  :Temp4 = 2000 / 45;
end split
->Temp3: Frequency
Temp4: Duration; 
:A = Beep_Strength;
if (A == 0) then
  ->yes -> beeps are muted -> end;
  :ret;
  stop
endif
repeat
  :Temp2 = 2;
  repeat
    ->Complementary B FET off;
    :B_Com_Fet_Off;
    ->Allow some time after com FET is turned off;
    repeat
      :A = A - 1;
    repeat while (A != 0) is (yes)
    ->B pwm FET on (in order to charge the driver of the B com FET);
    :B_Pwm_Fet_On;
    ->Let the B pwm FET be turned on a while;
    repeat
      :A = A - 1;
    repeat while (A != 0) is (yes)
    ->B pwm FET off again;
    :B_Pwm_Fet_Off;
    ->Allow some time after B pwm FET is turned off;
    repeat
      :A = A - 1;
    repeat while (A != 0) is (yes)
    ->B complementary FET on;
    :B_Com_Fet_On;
    ->Allow some time after B pwm FET is turned on;
    repeat
      :A = A - 1;
    repeat while (A != 0) is (yes)
    ->Turn on pwm FET;
    :A = Temp2;
    if (A.0 == 0) then (yes)
      :A_Pwm_Fet_On;
    endif
    if (A.0 == 1) then (yes)
      :C_Pwm_Fet_On;
    endif
    ->On time according to beep strength;
    :A = Beep_Strength;
    repeat
      :A = A - 1;
    repeat while (A != 0) is (yes)
    ->Turn off pwm FET;
    :A = Temp2;
    if (A.0 == 0) then (yes)
      :A_Pwm_Fet_Off;
    endif
    if (A.0 == 1) then (yes)
      :C_Pwm_Fet_Off;
    endif
    ->Off for 25 us;
    :A = 150;
    repeat
      :A = A - 1;
    repeat while (A != 0) is (yes)
    :Temp2 = Temp2 - 1;
  repeat while (Temp2 != 0) is (yes)
  :A = Temp3;
  ->Off time according to beep frequency;
  repeat
    ->Fets off loop;
    :Temp1 = 200;
    repeat
      :Temp1 = Temp1 - 1;
    repeat while (Temp1 != 0) is (yes)
    :A = A - 1;
  repeat while (A != 0) is (yes)
  :Temp4 = Temp4 - 1;
->Number of beep pulses (duration);
repeat while (Temp4 != 0) is (yes)
:B_Com_Fet_Off;
:ret;
stop
@enduml



