name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  generate_plantuml:
    runs-on: ubuntu-latest
    name: plantuml
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get install graphviz
          sudo mkdir -p /opt/plantuml
          cd /opt/plantuml
          UML=https://github.com/plantuml/plantuml/releases/download/v1.2022.7/plantuml-1.2022.7.jar
          sudo curl -JLO ${UML}
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Process Diagrams
        run: java -jar /opt/plantuml/plantuml-1.2022.6.jar -v -tsvg -r -o "./puml/svgs" "./puml/**.puml"

  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: 'gh-pages'
